spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 256MB
      max-request-size: 256MB
  application:
    name: report
  data:
    mongodb:
      uri: mongodb://localhost:27017/tms

file.service.root: 'file-storage/'

server:
  port: 8282
logging:
  file:
    name: "${spring.application.name}.log"
    clean-history-on-start: true
  level:
    root: INFO
    org.springframework.web: DEBUG
